// ONLY MP3 With MetaData
const musicData = [
    {
        id: 0,
        title: 'Aaro Ekbar',
        artist: 'Rupam Islam',
        cover: 'https://pendujatt.com.se/uploads/album/fossils-vol-1-rupam-islam.webp',
        src: 'https://pagallworld.co.in/wp-content/uploads/2023/12/Aro-Ekbar.mp3',
    },
    {
        id: 1,
        title: 'Beete Lamhein The Train',
        artist: 'Kshitij Tarey',
        cover: 'https://pagalnew.com/coverimages/Beete-Lamhein-The-Train-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/9506',
    },
    {
        id: 2,
        title: 'Chahun Main Ya Naa',
        artist: 'Palak Muchhal',
        cover: 'https://pagalnew.com/coverimages/Chahun-Main-Ya-Naa-Aashiqui-2-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/6026',
    },
    {
        id: 3,
        title: 'Hariye Jawar Gaan',
        artist: 'Anupam Roy',
        cover: 'https://pendujatt.com.se/uploads/album/uma-original-motion-picture-soundtrack-anupam-roy.webp',
        src: 'https://bajaao.pendujatt.com.se/load/128/14837171/527285/Hariye Jawar Gaan.mp3',
    },
    {
        id: 4,
        title: 'Jiya Lage Na',
        artist: 'Ram Sampath',
        cover: 'https://pagalnew.com/coverimages/Jiya-Lage-Na-Talaash-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/6889',
    },
    {
        id: 5,
        title: 'Duniyaa',
        artist: 'Abhijit Vaghani',
        cover: 'https://pendujatt.com.se/uploads/album/luka-chuppi-various-artists.webp',
        src: 'https://bajaao.pendujatt.com.se/load/128/15194556/58349/Duniyaa.mp3',
    },
    {
        id: 6,
        title: 'O Rangrez Bhaag Milkha Bhaag',
        artist: 'Shankar-Ehsaan-Loy',
        cover: 'https://pagalnew.com/coverimages/O-Rangrez-Bhaag-Milkha-Bhaag-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/6157',
    },
    {
        id: 7,
        title: 'One Love',
        artist: 'Shubh',
        cover: 'https://pagalnew.com/coverimages/One-Love-Shubh-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/43180',
    },
    {
        id: 8,
        title: 'Ranjha',
        artist: 'B Praak',
        cover: 'https://pagalnew.com/coverimages/ranjha-shershaah-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/19111',
    },
    {
        id: 9,
        title: 'Sukoon',
        artist: 'Arijit Singh',
        cover: 'https://soundworldz.com/upload_file/10/230x230/thumb_68c8f0b964370.webp',
        src: 'https://songspk.com.se/files/download/type/128/id/114961',
    },
    {
        id: 10,
        title: 'Tere Mere Sapne Ab Ek Rang Hain',
        artist: 'S. D. Burman',
        cover: 'https://pagalnew.com/coverimages/Tere-Mere-Sapne-Ab-Ek-Rang-Hain-Guide-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/1494',
    },
    {
        id: 11,
        title: 'Tum Ko Dekha To Yeh Khayal Aaya',
        artist: 'Jagjit Singh',
        cover: 'https://pagalnew.com/coverimages/tum-ko-dekha-to-yeh-khayal-aaya-saath-saath-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/28630',
    },
    {
        id: 12,
        title: 'Afreen',
        artist: 'Rahat Fateh Ali Khan',
        cover: 'https://pagalnew.com/coverimages/afreen-afreen-rath-fateh-ali-khan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51655',
    },
    {
        id: 13,
        title: 'Bekaar Dil',
        artist: 'Vishal Mishra',
        cover: 'https://pagalnew.com/coverimages/Bekaar-Dil-Fighter-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/45439',
    },
    {
        id: 14,
        title: 'Jabra Fan',
        artist: 'Nakash Aziz',
        cover: 'https://pagalnew.com/coverimages/Jabra-Fan---Hindi-Version-Nakash-Aziz-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/3867',
    },
    {
        id: 15,
        title: 'Tum Jo Mile',
        artist: 'Abhijeet Srivastava',
        cover: 'https://pagalnew.com/coverimages/tum-jo-milo-freddy-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/36915',
    },
    {
        id: 16,
        title: 'Catch Me If U Can',
        artist: 'Amaal Mallik',
        cover: 'https://pagalnew.com/coverimages/Catch-Me-If-U-Can-Force-2-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/4123',
    },
    {
        id: 17,
        title: 'Aap Is Dhoop Mein',
        artist: 'Arijit Singh',
        cover: 'https://pagalnew.com/coverimages/aap-is-dhoop-mein-gustaakh-ishq-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52475',
    },
    {
        id: 18,
        title: 'Main Nikla Gaddi Leke',
        artist: 'Udit Narayan',
        cover: 'https://pagalnew.com/coverimages/main-nikla-gaddi-leke-gadar-2-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/43007',
    },
    {
        id: 19,
        title: 'Raghupati Raghava Raja Ram',
        artist: 'A.R. Rahman',
        cover: 'https://pagalnew.com/coverimages/raghupati-raghava-raja-ram-gandhi-godse-ek-yudh-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/38110',
    },
    {
        id: 20,
        title: 'Ghar Nahi Jaana',
        artist: 'Zahrah Khan',
        cover: 'https://pagalnew.com/coverimages/ghar-nahi-jaanagumraah-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/39041',
    },
    {
        id: 21,
        title: 'Qubool',
        artist: 'Armaan Khan',
        cover: 'https://pagalnew.com/coverimages/qubool-haq-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52489',
    },
    {
        id: 22,
        title: 'Laal Pari',
        artist: 'Yo Yo Honey Singh',
        cover: 'https://pagalnew.com/coverimages/laal-pari-housefull-5-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51332',
    },
    {
        id: 23,
        title: 'Daiyya Daiyya',
        artist: 'Neha Kakkar',
        cover: 'https://pagalnew.com/coverimages/daiyya-daiyya-hunter-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/39044',
    },
    {
        id: 24,
        title: 'Dil Melt Karda',
        artist: 'Navraj Hans',
        cover: 'https://pagalnew.com/coverimages/Dil-Melt-Karda-From-Haseen-Dillruba-Navraj-Hans-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/17411',
    },
    {
        id: 25,
        title: 'Koi Aayat',
        artist: 'Sukanya Purkayastha',
        cover: 'https://pagalnew.com/coverimages/Koi-Aayat-Indian-Police-Force-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/45039',
    },
    {
        id: 26,
        title: 'Darbadar',
        artist: 'Jubin Nautiyal',
        cover: 'https://pagalnew.com/coverimages/darbadar-ittu-si-baat-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/27444',
    },
    {
        id: 27,
        title: 'Dil Ghabraye',
        artist: 'Taba Chake',
        cover: 'https://pagalnew.com/coverimages/dil-ghabraye-i-want-to-talk-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/49473',
    },
    {
        id: 28,
        title: 'Aashiqui',
        artist: 'Raj Barman',
        cover: 'https://pagalnew.com/coverimages/Aashiqui-Ishq-Pashmina-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/33727',
    },
    {
        id: 29,
        title: 'Jaadu',
        artist: 'Raghav Chaitanya',
        cover: 'https://pagalnew.com/coverimages/jaadu-jewel-thief-the-heist-begins-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51155',
    },
    {
        id: 30,
        title: 'Glass Uchhi Rakhey',
        artist: 'Meggha Bali',
        cover: 'https://pagalnew.com/coverimages/glass-uchhi-rakhey-jolly-llb-3-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52088',
    },
    {
        id: 31,
        title: 'Chaleya',
        artist: 'Arijit Singh',
        cover: 'https://pagalnew.com/coverimages/chaleya-jawan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/43094',
    },
    {
        id: 32,
        title: 'Dil E Nadaan',
        artist: 'Tushar Lall',
        cover: 'https://pagalnew.com/coverimages/dilenadaan-jo-tera-hai-woh-mera-hai-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/48957',
    },
    {
        id: 33,
        title: 'Brahmakalasha',
        artist: 'Abby V',
        cover: 'https://pagalnew.com/coverimages/brahmakalasha-kantara-a-legend-chapter-1-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52395',
    },
    {
        id: 34,
        title: 'Pighal Ke Panahon Mein',
        artist: 'Shaan',
        cover: 'https://pagalnew.com/coverimages/pighal-ke-panahon-mein-kesari-veer-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51459',
    },
    {
        id: 35,
        title: 'Baari Barsi',
        artist: 'Guru Randhawa',
        cover: 'https://pagalnew.com/coverimages/Baari-Barsi-Khel-Khel-Mein-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/48217',
    },
    {
        id: 36,
        title: 'Jaako Raakhe Saaiyan',
        artist: 'Monu Rathod',
        cover: 'https://pagalnew.com/coverimages/jaako-raakhe-saaiyan-kill-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/47618',
    },
    {
        id: 37,
        title: 'Chahe Jo Ho',
        artist: 'Jubin Nautiyal',
        cover: 'https://pagalnew.com/coverimages/chahe-jo-ho-love-in-vietnam-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52250',
    },
    {
        id: 38,
        title: 'Beda Paar',
        artist: 'Sona Mohapatra',
        cover: 'https://pagalnew.com/coverimages/Beda-Paar-Laapataa-Ladies-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/45582',
    },
    {
        id: 39,
        title: 'Tera Hi Jaadu Hai',
        artist: 'Raqueeb Alam',
        cover: 'https://pagalnew.com/coverimages/tera-hi-jaadu-hai-leo-hindi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/44140',
    },
    {
        id: 40,
        title: 'Kahani',
        artist: 'Mohan Kannan',
        cover: 'https://pagalnew.com/coverimages/kahani-laal-singh-chaddha-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/26098',
    },
    {
        id: 41,
        title: 'Aaoge Jab Tum',
        artist: 'Ustad Rashid Khan',
        cover: 'https://pagalnew.com/coverimages/Aaoge-Jab-Tum-Jab-We-Met-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/9297',
    },
    {
        id: 42,
        title: 'Aas Paas Hai Khuda',
        artist: 'Rahat Fateh Ali Khan',
        cover: 'https://pagalnew.com/coverimages/Aas-Paas-Hai-Khuda-Unplugged-Anjaana-Anjaani-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/8019',
    },
    {
        id: 43,
        title: 'Aaja Nachle',
        artist: 'Sunidhi Chauhan',
        cover: 'https://pagalnew.com/covercovers/Aaja-Nachle-Sunidhi-Chauhan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/9051',
    },
    {
        id: 44,
        title: 'Aao Milo Chalo',
        artist: 'Pritam',
        cover: 'https://pagalnew.com/covercovers/Aao-Milo-Chalo-Jab-We-Met-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/9296',
    },
    {
        id: 45,
        title: 'Bulleya',
        artist: 'Pritam',
        cover: 'https://pagalnew.com/covercovers/Bulleya-Ae-Dil-Hai-Mushkil-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/4098',
    },
    {
        id: 46,
        title: 'Galatfehmi',
        artist: 'Tushar Joshi',
        cover: 'https://pagalnew.com/coverimages/galatfehmi-nadaaniyan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/50356',
    },
    {
        id: 47,
        title: 'Ishq Mein',
        artist: 'Nadaaniyan',
        cover: 'https://pagalnew.com/coverimages/ishq-mein-nadaaniyan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/50325',
    },
    {
        id: 48,
        title: 'Galatfehmi Female Version',
        artist: 'Madhubanti Bagchi',
        cover: 'https://pagalnew.com/coverimages/galatfehmi-female-version-nadaaniyan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/50572',
    },
    {
        id: 49,
        title: 'Aanan Faanan Mehfil Mix',
        artist: 'Jayesh Gandhi',
        cover: 'https://pagalnew.com/coverimages/Aanan-Faanan-Mehfil-Mix-Namastey-London-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/9361',
    },
    {
        id: 50,
        title: 'Aha Aha',
        artist: 'Udit Narayan',
        cover: 'https://pagalnew.com/128-downloads/12245',
        src: 'https://pagalnew.com/coverimages/Aha-Aha-Na-Tum-Jaano-Na-Hum-500-500.jpg',
    },
    {
        id: 51,
        title: 'Chanda Sitare',
        artist: 'Udit Narayan',
        cover: 'https://pagalnew.com/coverimages/chanda-sitare-naseeb-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/15032',
    },
    {
        id: 52,
        title: 'Kabhi Jo Bhoolna Chahoon',
        artist: 'Kumar Sanu',
        cover: 'https://pagalnew.com/coverimages/kabhi-jo-bhoolna-chahoon-naseeb-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/15034',
    },
    {
        id: 53,
        title: 'Churaa Lenge',
        artist: 'Kumar Sanu',
        cover: 'https://pagalnew.com/coverimages/churaa-lenge-naseeb-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/15033',
    },
    {
        id: 54,
        title: 'Seene Pe',
        artist: 'Kavita Krishnamurthy',
        cover: 'https://pagalnew.com/coverimages/seene-pe-naseeb-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/15035',
    },
    {
        id: 55,
        title: 'Shikwa Nahin Kisi Se',
        artist: 'Kumar Sanu',
        cover: 'https://pagalnew.com/coverimages/shikwa-nahin-kisi-se-naseeb-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/15036',
    },
    {
        id: 56,
        title: 'Ek Ladki Bheegi Bhagi Si',
        artist: 'Shashwat Singh',
        cover: 'https://pagalnew.com/coverimages/ek-ladki-bheegi-bhagi-si-kahan-shuru-kahan-khatam-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/48764',
    },
    {
        id: 57,
        title: 'Sehra',
        artist: 'Dhvani Bhanushali',
        cover: 'https://pagalnew.com/coverimages/sehra-kahan-shuru-kahan-khatam-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/48837',
    },
    {
        id: 58,
        title: 'Rang Udaye',
        artist: 'Varun Jain',
        cover: 'https://pagalnew.com/coverimages/rang-udaye-kahan-shuru-kahan-khatam-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/48854',
    },
    {
        id: 59,
        title: 'Bhairava Anthem',
        artist: 'Diljit Dosanjh',
        cover: 'https://pagalnew.com/coverimages/bhairava-anthem-kalki-2898-ad-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/47120',
    },
    {
        id: 60,
        title: 'A World Of Treasures',
        artist: 'Santhosh Narayanan',
        cover: 'https://pagalnew.com/coverimages/a-world-of-treasures-kalki-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/47816',
    },
    {
        id: 61,
        title: 'Ashwathama',
        artist: 'Santhosh Narayanan',
        cover: 'https://pagalnew.com/coverimages/ashwathama-kalki-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/47819',
    },
    {
        id: 62,
        title: 'Agriculture',
        artist: 'Arafat Mohamood',
        cover: 'https://pagalnew.com/coverimages/agriculture-kantara-a-legend-chapter-1-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52476',
    },
    {
        id: 63,
        title: 'Brahmakalasha',
        artist: 'Abby V',
        cover: 'https://pagalnew.com/coverimages/brahmakalasha-kantara-a-legend-chapter-1-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52395',
    },
    {
        id: 64,
        title: 'Rebel',
        artist: 'Diljit Dosanjh',
        cover: 'https://pagalnew.com/coverimages/rebel-kantara-a-legend-chapter-1-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52396',
    },
    {
        id: 65,
        title: 'Jaako Raakhe Saaiyan',
        artist: 'Monu Rathod',
        cover: 'https://pagalnew.com/coverimages/jaako-raakhe-saaiyan-kill-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/47618',
    },
    {
        id: 66,
        title: 'Baari Barsi',
        artist: 'Guru Randhawa',
        cover: 'https://pagalnew.com/coverimages/Baari-Barsi-Khel-Khel-Mein-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/48217',
    },
    {
        id: 67,
        title: 'Hauli Hauli',
        artist: 'Yo Yo Honey Singh',
        cover: 'https://pagalnew.com/coverimages/hauli-hauli-khel-khel-mein-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/47901',
    },
    {
        id: 68,
        title: 'Duur Na Karin',
        artist: 'Vishal Mishra',
        cover: 'https://pagalnew.com/coverimages/duur-na-karin-khel-khel-mein-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/48006',
    },
    {
        id: 69,
        title: 'Title Track',
        artist: 'Snigdhajit Bhowmik',
        cover: 'https://pagalnew.com/coverimages/title-track-kabzaa-hindi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/38111',
    },
    {
        id: 70,
        title: 'Baahon Mein Teri',
        artist: 'Ankur Tewari',
        cover: 'https://pagalnew.com/coverimages/Baahon-Mein-Teri-Kho-Gaye-Hum-Kahan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/44939',
    },
    {
        id: 71,
        title: 'Hone Do Jo Hota Hai',
        artist: 'OAFF',
        cover: 'https://pagalnew.com/coverimages/Hone-Do-Jo-Hota-Hai-Kho-Gaye-Hum-Kahan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/44936',
    },
    {
        id: 72,
        title: 'Teri Yeh Baatein',
        artist: 'Savera',
        cover: 'https://pagalnew.com/coverimages/Teri-Yeh-Baatein-Kho-Gaye-Hum-Kahan-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/44938',
    },
    {
        id: 73,
        title: 'Title Track',
        artist: 'Achint',
        cover: 'https://pagalnew.com/coverimages/Kho-Gaye-Hum-Kahan-Javed-Akhtar-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/44941',
    },

    {
        id: 74,
        title: 'Channa Tu Bemisal',
        artist: 'Jubin Nautiyal',
        cover: 'https://pagalnew.com/coverimages/Channa-Tu-Bemisal-Mere-Husband-Ki-Biwi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/50355',
    },
    {
        id: 75,
        title: 'Aarti Version Namaste',
        artist: 'Aparna Harikumar',
        cover: 'https://pagalnew.com/coverimages/aarti-version-namaste-mahavatar-narsimha-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52010',
    },
    {
        id: 76,
        title: 'Asura Theme',
        artist: 'The Shloka',
        cover: 'https://pagalnew.com/coverimages/asura-theme-mahavatar-narsimha-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/52011',
    },
    {
        id: 77,
        title: 'Aur Mohabbat Kitni Karoon',
        artist: 'Arijit Singh',
        cover: 'https://pagalnew.com/coverimages/aur-mohabbat-kitni-karoon-metro-in-dino-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51817',
    },
    {
        id: 78,
        title: 'Mann Ye Mera',
        artist: 'Vishal Mishra',
        cover: 'https://pagalnew.com/coverimages/mann-ye-mera-metro-in-dino-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51799',
    },
    {
        id: 79,
        title: 'Dil Ka Kya',
        artist: 'Raghav Chaitanya',
        cover: 'https://pagalnew.com/coverimages/dil-ka-kya-metro-in-dino-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51798',
    },
    {
        id: 80,
        title: 'Dhaagena Tinak Dhin',
        artist: 'Sachet Tandon, Akasa',
        cover: 'https://pagalnew.com/coverimages/dhaagena-tinak-dhin-metro-in-dino-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51823',
    },
    {
        id: 81,
        title: 'Yaad',
        artist: 'Papon',
        cover: 'https://pagalnew.com/coverimages/yaad-metro-in-dino-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51825',
    },
    {
        id: 82,
        title: 'Mausam',
        artist: 'Arijit Singh',
        cover: 'https://pagalnew.com/coverimages/mausam-metro-in-dino-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51824',
    },
    {
        id: 83,
        title: 'Dekhha Tenu',
        artist: 'Mohammad Faiz',
        cover: 'https://pagalnew.com/coverimages/dekhha-tenu-mr-and-mrs-mahi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46751',
    },
    {
        id: 84,
        title: 'Agar Ho Tum',
        artist: 'Jubin Nautiyal',
        cover: 'https://pagalnew.com/coverimages/agar-ho-tum-mr-and-mrs-mahi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46772',
    },
    {
        id: 85,
        title: 'Ranjhana',
        artist: 'Dhrruv Dhalla',
        cover: 'https://pagalnew.com/coverimages/ranjhana-mr-and-mrs-mahi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46806',
    },
    {
        id: 86,
        title: 'Roya Jab Tu',
        artist: 'Vishal Mishra, Azeem Dayani',
        cover: 'https://pagalnew.com/coverimages/roya-jab-tu-mr-and-mrs-mahi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46807',
    },
    {
        id: 87,
        title: 'Tu Hain Toh Neeti Version',
        artist: 'Hunny',
        cover: 'https://pagalnew.com/coverimages/tu-hain-toh-neeti-version-mr-and-mrs-mahi-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46809',
    },
    {
        id: 88,
        title: 'Tujhse Pyaar Hai',
        artist: 'Anweshaa, Tushar Joshi, Akshay Menon',
        cover: 'https://pagalnew.com/coverimages/tujhse-pyaar-hai-main-ladega-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46813',
    },
    {
        id: 89,
        title: 'Maai Meri',
        artist: 'Vaishnavi Thakur',
        cover: 'https://pagalnew.com/coverimages/maai-meri-main-ladega-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46812',
    },
    {
        id: 90,
        title: 'Main Ladega Anthem',
        artist: 'Romy',
        cover: 'https://pagalnew.com/coverimages/title-anthem-main-ladega-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/46354',
    },
    {
        id: 91,
        title: 'Pee Loon',
        artist: 'Pritam',
        cover: 'https://pagalnew.com/coverimages/Pee-Loon-Once-Upon-A-Time-In-Mumbaai-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/7915',
    },
    {
        id: 92,
        title: 'Tum Jo Aaye Jindagi',
        artist: 'Rahat Fateh Ali Khan',
        cover: 'https://pagalnew.com/coverimages/Tum-Jo-Aaye-Jindagi-Once-Upon-A-Time-In-Mumbaai-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/7914',
    },
    {
        id: 93,
        title: 'I Am In Love Dance',
        artist: 'Pritam',
        cover: 'https://pagalnew.com/coverimages/I-Am-In-Love-Dance-Once-Upon-A-Time-In-Mumbaai-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/7921',
    },
    {
        id: 94,
        title: 'Babu Rao',
        artist: 'Pritam',
        cover: 'https://pagalnew.com/coverimages/Babu-Rao-Once-Upon-A-Time-In-Mumbaai-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/7918',
    },
    {
        id: 95,
        title: 'Barbaad',
        artist: 'Jubin Nautiyal',
        cover: 'https://pagalnew.com/coverimages/barbaad-saiyaara-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51747',
    },
    {
        id: 96,
        title: 'Tum Ho Toh',
        artist: 'Vishal Mishra',
        cover: 'https://pagalnew.com/coverimages/tum-ho-toh-saiyaara-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51800',
    },
    {
        id: 97,
        title: 'Barbaad Reprise Female',
        artist: 'Shilpa Rao',
        cover: 'https://pagalnew.com/coverimages/barbaad-reprise-female-saiyaara-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51956',
    },
    {
        id: 98,
        title: 'Saiyaara Reprise Female',
        artist: 'Shreya Ghoshal',
        cover: 'https://pagalnew.com/coverimages/saiyaara-reprise-female-saiyaara-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/51957',
    },
    {
        id: 99,
        title: 'Rafta Rafta Medley',
        artist: 'Vishal Mishra',
        cover: 'https://pagalnew.com/coverimages/Rafta-Rafta-Medley-Yamla-Pagla-Deewana-Phir-Se-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/2915',
    },
    {
        id: 100,
        title: 'Do Peg Maar',
        artist: 'Neha Kakkar',
        cover: 'https://pagalnew.com/coverimages/Do-Peg-Maar-One-Night-Stand-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/3909',
    },
    {
        id: 101,
        title: 'Saajan Aayo Re',
        artist: 'A.R. Rahman, Jonita Gandhi',
        cover: 'https://pagalnew.com/coverimages/Saajan-Aayo-Re-OK-Jaanu-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/3331',
    },
    {
        id: 102,
        title: 'Khwahishe Rooh Ki',
        artist: 'Dev Arijit',
        cover: 'https://pagalnew.com/coverimages/khwahishe-rooh-ki-operation-mayfair-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/39037',
    },
    {
        id: 103,
        title: 'Happy Days',
        artist: 'Abhijeet',
        cover: 'https://pagalnew.com/coverimages/Happy-Days-Om-Jai-Jagadish-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/12257',
    },
    {
        id: 104,
        title: 'Om Jai Jagadish',
        artist: 'Abhijeet',
        cover: 'https://pagalnew.com/coverimages/Om-Jai-Jagadish-Version-2-Abhijeet-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/12259',
    },
    {
        id: 105,
        title: 'Eyy Bidda Ye Mera Adda',
        artist: 'Nakash Aziz',
        cover: 'https://pagalnew.com/coverimages/eyy-bidda-ye-mera-adda-pushpa-the-rise-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/23013',
    },
    {
        id: 106,
        title: 'Oo Bolega Ya Oo Oo Bolega',
        artist: 'Kanika Kapoor',
        cover: 'https://pagalnew.com/coverimages/oo-bolega-ya-oo-oo-bolega-pushpa-the-rise-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/23014',
    },
    {
        id: 107,
        title: 'Bhagwan Hai Kahan Re Tu',
        artist: 'Shantanu Moitra, Sonu Nigam',
        cover: 'https://pagalnew.com/coverimages/Bhagwan-Hai-Kahan-Re-Tu-PK-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/4947',
    },
    {
        id: 108,
        title: 'Love Is A Waste Of Time',
        artist: 'Shantanu Moitra',
        cover: 'https://pagalnew.com/coverimages/Love-Is-A-Waste-Of-Time-PK-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/4946',
    },
    {
        id: 109,
        title: 'Back Marti Hain Male',
        artist: 'Mohammed Aziz',
        cover: 'https://pagalnew.com/coverimages/Back-Marti-Hain-Male-Police-Officer-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/17422',
    },
    {
        id: 110,
        title: 'Back Marta Hai Female',
        artist: 'Sadhana Sargam',
        cover: 'https://pagalnew.com/coverimages/Back-Marta-Hai-Female-Police-Officer-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/17421',
    },
    {
        id: 111,
        title: 'Aitbaar Nahi Karna Duet Version',
        artist: 'Abhijeet, Sadhana Sargam',
        cover: 'https://pagalnew.com/coverimages/Aitbaar-Nahi-Karna-Duet-Version-Qayamat-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/11527',
    },
    {
        id: 112,
        title: 'Mera Dil Dil Tu Lele',
        artist: 'Shaan, Mahalaxmi',
        cover: 'https://pagalnew.com/coverimages/Mera-Dil-Dil-Tu-Lele-Qayamat-500-500.jpg',
        src: 'https://pagalnew.com/128-downloads/11530',
    },
];

export default musicData;
