// ONLY MP3 With MetaData
const musicData = [
  {
    id: 0,
    title: 'Aaro Ekbar (PenduJatt)',
    artist: 'Fossils',
    cover: '/img/Aaro-Ekbar-(PenduJatt).png',
    src: '/music/Aaro-Ekbar-(PenduJatt).mp3',
  },
  {
    id: 1,
    title: 'Beete Lamhein The Train',
    artist: 'Mithoon',
    cover: '/img/Beete-Lamhein-The-Train.jpg',
    src: '/music/Beete-Lamhein-The-Train.mp3',
  },
  {
    id: 2,
    title: 'Chahun Main Ya Naa Aashiqui 2',
    artist: 'Arijit Singh',
    cover: '/img/Chahun-Main-Ya-Naa-Aashiqui-2.jpg',
    src: '/music/Chahun-Main-Ya-Naa-Aashiqui-2.mp3',
  },
  {
    id: 3,
    title: 'Hariye Jawar Gaan (PenduJatt)',
    artist: 'Anupam Roy',
    cover: '/img/Hariye-Jawar-Gaan-(PenduJatt).jpg',
    src: '/music/Hariye-Jawar-Gaan-(PenduJatt).mp3',
  },
  {
    id: 4,
    title: 'Jiya Lage Na Talaash',
    artist: 'Sona Mahapatra',
    cover: '/img/Jiya-Lage-Na-Talaash.jpg',
    src: '/music/Jiya-Lage-Na-Talaash.mp3',
  },
  {
    id: 5,
    title: 'O Rangrez Bhaag Milkha Bhaag',
    artist: 'Shreya Ghoshal',
    cover: '/img/O-Rangrez-Bhaag-Milkha-Bhaag.jpg',
    src: '/music/O-Rangrez-Bhaag-Milkha-Bhaag.mp3',
  },
  {
    id: 6,
    title: 'One Love Shubh',
    artist: 'Shubh',
    cover: '/img/One-Love-Shubh.jpg',
    src: '/music/One-Love-Shubh.mp3',
  },
  {
    id: 7,
    title: 'Sukoon',
    artist: 'Arijit Singh',
    cover: '/img/Sukoon.jpg',
    src: '/music/Sukoon.mp3',
  },
  {
    id: 8,
    title: 'Tere Mere Sapne Ab Ek Rang Hain',
    artist: 'Mohammed Rafi',
    cover: '/img/Tere-Mere-Sapne-Ab-Ek-Rang-Hain.jpg',
    src: '/music/Tere-Mere-Sapne-Ab-Ek-Rang-Hain.mp3',
  },
  {
    id: 9,
    title: 'Tum Ko Dekha To Yeh Khayal Aaya Saath Saath',
    artist: 'Jagjit Singh',
    cover: '/img/Tum-Ko-Dekha-To-Yeh-Khayal-Aaya-Saath-Saath.jpg',
    src: '/music/Tum-Ko-Dekha-To-Yeh-Khayal-Aaya-Saath-Saath.mp3',
  },
  {
    id: 10,
    title: 'Ranjha',
    artist: 'B Praak',
    cover: '/img/Ranjha.png',
    src: '/music/Ranjha.mp3',
  },
  {
    id: 11,
    title: 'Luka Chuppi Duniyaa',
    artist: 'Akhil',
    cover: '/img/Luka-Chuppi-Duniyaa.jpg',
    src: '/music/Luka-Chuppi-Duniyaa.mp3',
  },
  {
    id: 12,
    title: 'miracle-11151',
    artist: 'Mixkit',
    cover: '/img/pexels-thepaintedsquare.jpg',
    src: '/music/miracle-11151.mp3',
  },
  {
    id: 13,
    title: 'product-presentation-advertisement-music-320720',
    artist: 'Presentation advertis',
    cover: '/img/pexels-xexusdesigner.jpg',
    src: '/music/product-presentation-advertisement-music-320720.mp3',
  },
  {
    id: 14,
    title: 'upbeat-motivational',
    artist: 'upbeat motivational',
    cover: '/img/pexels-pixabay.jpg',
    src: '/music/upbeat-motivational-172092.mp3',
  },
];

export default musicData;
