// ONLY MP3 With MetaData
const musicData = [
  {
    id: 0,
    title: 'Aaro Ekbar',
    artist: 'Rupam Islam',
    cover:
      'https://pendujatt.com.se/uploads/album/fossils-vol-1-rupam-islam.webp',
    src: 'https://pagallworld.co.in/wp-content/uploads/2023/12/Aro-Ekbar.mp3',
  },
  {
    id: 1,
    title: 'Beete Lamhein The Train',
    artist: 'Kshitij Tarey',
    cover:
      'https://pagalnew.com/coverimages/Beete-Lamhein-The-Train-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/9506',
  },
  {
    id: 2,
    title: 'Chahun Main Ya Naa',
    artist: 'Palak Muchhal',
    cover:
      'https://pagalnew.com/coverimages/Chahun-Main-Ya-Naa-Aashiqui-2-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/6026',
  },
  {
    id: 3,
    title: 'Hariye Jawar Gaan',
    artist: 'Anupam Roy',
    cover:
      'https://pendujatt.com.se/uploads/album/uma-original-motion-picture-soundtrack-anupam-roy.webp',
    src: 'https://bajaao.pendujatt.com.se/load/128/14837171/527285/Hariye Jawar Gaan.mp3',
  },
  {
    id: 4,
    title: 'Jiya Lage Na',
    artist: 'Ram Sampath',
    cover: 'https://pagalnew.com/coverimages/Jiya-Lage-Na-Talaash-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/6889',
  },
  {
    id: 5,
    title: 'Duniyaa',
    artist: 'Abhijit Vaghani',
    cover:
      'https://pendujatt.com.se/uploads/album/luka-chuppi-various-artists.webp',
    src: 'https://bajaao.pendujatt.com.se/load/128/15194556/58349/Duniyaa.mp3',
  },
  {
    id: 6,
    title: 'O Rangrez Bhaag Milkha Bhaag',
    artist: 'Shankar-Ehsaan-Loy',
    cover:
      'https://pagalnew.com/coverimages/O-Rangrez-Bhaag-Milkha-Bhaag-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/6157',
  },
  {
    id: 7,
    title: 'One Love',
    artist: 'Shubh',
    cover: 'https://pagalnew.com/coverimages/One-Love-Shubh-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/43180',
  },
  {
    id: 8,
    title: 'Ranjha',
    artist: 'B Praak',
    cover: 'https://pagalnew.com/coverimages/ranjha-shershaah-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/19111',
  },
  {
    id: 9,
    title: 'Sukoon',
    artist: 'Arijit Singh',
    cover:
      'https://soundworldz.com/upload_file/10/230x230/thumb_68c8f0b964370.webp',
    src: 'https://songspk.com.se/files/download/type/128/id/114961',
  },
  {
    id: 10,
    title: 'Tere Mere Sapne Ab Ek Rang Hain',
    artist: 'S. D. Burman',
    cover:
      'https://pagalnew.com/coverimages/Tere-Mere-Sapne-Ab-Ek-Rang-Hain-Guide-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/1494',
  },
  {
    id: 11,
    title: 'Tum Ko Dekha To Yeh Khayal Aaya',
    artist: 'Jagjit Singh',
    cover:
      'https://pagalnew.com/coverimages/tum-ko-dekha-to-yeh-khayal-aaya-saath-saath-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/28630',
  },
  {
    id: 12,
    title: 'Afreen',
    artist: 'Rahat Fateh Ali Khan',
    cover:
      'https://pagalnew.com/coverimages/afreen-afreen-rath-fateh-ali-khan-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/51655',
  },
  {
    id: 13,
    title: 'Bekaar Dil',
    artist: 'Vishal Mishra',
    cover: 'https://pagalnew.com/coverimages/Bekaar-Dil-Fighter-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/45439',
  },
  {
    id: 14,
    title: 'Jabra Fan',
    artist: 'Nakash Aziz',
    cover:
      'https://pagalnew.com/coverimages/Jabra-Fan---Hindi-Version-Nakash-Aziz-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/3867',
  },
  {
    id: 15,
    title: 'Tum Jo Mile',
    artist: 'Abhijeet Srivastava',
    cover: 'https://pagalnew.com/coverimages/tum-jo-milo-freddy-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/36915',
  },
  {
    id: 16,
    title: 'Catch Me If U Can',
    artist: 'Amaal Mallik',
    cover:
      'https://pagalnew.com/coverimages/Catch-Me-If-U-Can-Force-2-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/4123',
  },
  {
    id: 17,
    title: 'Aap Is Dhoop Mein',
    artist: 'Arijit Singh',
    cover:
      'https://pagalnew.com/coverimages/aap-is-dhoop-mein-gustaakh-ishq-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/52475',
  },
  {
    id: 18,
    title: 'Main Nikla Gaddi Leke',
    artist: 'Udit Narayan',
    cover:
      'https://pagalnew.com/coverimages/main-nikla-gaddi-leke-gadar-2-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/43007',
  },
  {
    id: 19,
    title: 'Raghupati Raghava Raja Ram',
    artist: 'A.R. Rahman',
    cover:
      'https://pagalnew.com/coverimages/raghupati-raghava-raja-ram-gandhi-godse-ek-yudh-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/38110',
  },
  {
    id: 20,
    title: 'Ghar Nahi Jaana',
    artist: 'Zahrah Khan',
    cover:
      'https://pagalnew.com/coverimages/ghar-nahi-jaanagumraah-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/39041',
  },
  {
    id: 21,
    title: 'Qubool',
    artist: 'Armaan Khan',
    cover: 'https://pagalnew.com/coverimages/qubool-haq-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/52489',
  },
  {
    id: 22,
    title: 'Laal Pari',
    artist: 'Yo Yo Honey Singh',
    cover: 'https://pagalnew.com/coverimages/laal-pari-housefull-5-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/51332',
  },
  {
    id: 23,
    title: 'Daiyya Daiyya',
    artist: 'Neha Kakkar',
    cover: 'https://pagalnew.com/coverimages/daiyya-daiyya-hunter-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/39044',
  },
  {
    id: 24,
    title: 'Dil Melt Karda',
    artist: 'Navraj Hans',
    cover:
      'https://pagalnew.com/coverimages/Dil-Melt-Karda-From-Haseen-Dillruba-Navraj-Hans-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/17411',
  },
  {
    id: 25,
    title: 'Koi Aayat',
    artist: 'Sukanya Purkayastha',
    cover:
      'https://pagalnew.com/coverimages/Koi-Aayat-Indian-Police-Force-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/45039',
  },
  {
    id: 26,
    title: 'Darbadar',
    artist: 'Jubin Nautiyal',
    cover: 'https://pagalnew.com/coverimages/darbadar-ittu-si-baat-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/27444',
  },
  {
    id: 27,
    title: 'Dil Ghabraye',
    artist: 'Taba Chake',
    cover:
      'https://pagalnew.com/coverimages/dil-ghabraye-i-want-to-talk-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/49473',
  },
  {
    id: 28,
    title: 'Aashiqui',
    artist: 'Raj Barman',
    cover:
      'https://pagalnew.com/coverimages/Aashiqui-Ishq-Pashmina-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/33727',
  },
  {
    id: 29,
    title: 'Jaadu',
    artist: 'Raghav Chaitanya',
    cover:
      'https://pagalnew.com/coverimages/jaadu-jewel-thief-the-heist-begins-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/51155',
  },
  {
    id: 30,
    title: 'Glass Uchhi Rakhey',
    artist: 'Meggha Bali',
    cover:
      'https://pagalnew.com/coverimages/glass-uchhi-rakhey-jolly-llb-3-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/52088',
  },
  {
    id: 31,
    title: 'Chaleya',
    artist: 'Arijit Singh',
    cover: 'https://pagalnew.com/coverimages/chaleya-jawan-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/43094',
  },
  {
    id: 32,
    title: 'Dil E Nadaan',
    artist: 'Tushar Lall',
    cover:
      'https://pagalnew.com/coverimages/dilenadaan-jo-tera-hai-woh-mera-hai-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/48957',
  },
  {
    id: 33,
    title: 'Brahmakalasha',
    artist: 'Abby V',
    cover:
      'https://pagalnew.com/coverimages/brahmakalasha-kantara-a-legend-chapter-1-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/52395',
  },
  {
    id: 34,
    title: 'Pighal Ke Panahon Mein',
    artist: 'Shaan',
    cover:
      'https://pagalnew.com/coverimages/pighal-ke-panahon-mein-kesari-veer-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/51459',
  },
  {
    id: 35,
    title: 'Baari Barsi',
    artist: 'Guru Randhawa',
    cover:
      'https://pagalnew.com/coverimages/Baari-Barsi-Khel-Khel-Mein-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/48217',
  },
  {
    id: 36,
    title: 'Jaako Raakhe Saaiyan',
    artist: 'Monu Rathod',
    cover:
      'https://pagalnew.com/coverimages/jaako-raakhe-saaiyan-kill-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/47618',
  },
  {
    id: 37,
    title: 'Chahe Jo Ho',
    artist: 'Jubin Nautiyal',
    cover:
      'https://pagalnew.com/coverimages/chahe-jo-ho-love-in-vietnam-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/52250',
  },
  {
    id: 38,
    title: 'Beda Paar',
    artist: 'Sona Mohapatra',
    cover:
      'https://pagalnew.com/coverimages/Beda-Paar-Laapataa-Ladies-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/45582',
  },
  {
    id: 39,
    title: 'Tera Hi Jaadu Hai',
    artist: 'Raqueeb Alam',
    cover:
      'https://pagalnew.com/coverimages/tera-hi-jaadu-hai-leo-hindi-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/44140',
  },
  {
    id: 40,
    title: 'Kahani',
    artist: 'Mohan Kannan',
    cover:
      'https://pagalnew.com/coverimages/kahani-laal-singh-chaddha-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/26098',
  },
  {
    id: 41,
    title: 'Aaoge Jab Tum',
    artist: 'Ustad Rashid Khan',
    cover:
      'https://pagalnew.com/coverimages/Aaoge-Jab-Tum-Jab-We-Met-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/9297',
  },
  {
    id: 42,
    title: 'Aas Paas Hai Khuda',
    artist: 'Rahat Fateh Ali Khan',
    cover:
      'https://pagalnew.com/coverimages/Aas-Paas-Hai-Khuda-Unplugged-Anjaana-Anjaani-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/8019',
  },
  {
    id: 43,
    title: 'Aaja Nachle',
    artist: 'Sunidhi Chauhan',
    cover:
      'https://pagalnew.com/covercovers/Aaja-Nachle-Sunidhi-Chauhan-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/9051',
  },
  {
    id: 44,
    title: 'Aao Milo Chalo',
    artist: 'Pritam',
    cover:
      'https://pagalnew.com/covercovers/Aao-Milo-Chalo-Jab-We-Met-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/9296',
  },
  {
    id: 45,
    title: 'Bulleya',
    artist: 'Pritam',
    cover:
      'https://pagalnew.com/covercovers/Bulleya-Ae-Dil-Hai-Mushkil-500-500.jpg',
    src: 'https://pagalnew.com/128-downloads/4098',
  },
  {
    id: 46,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 47,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 48,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 49,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 50,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 51,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 52,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 53,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 54,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 55,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 56,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 57,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 58,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 59,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 60,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 61,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 62,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 63,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 64,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 65,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 66,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 67,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 68,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 69,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 70,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 71,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 72,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 73,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 74,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 75,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 76,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 77,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 78,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 79,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 80,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 81,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 82,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 83,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 84,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 85,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 86,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 87,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 88,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 89,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 90,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 91,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 92,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 93,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 94,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 95,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 96,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 97,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 98,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 99,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 100,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 101,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 102,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 103,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 104,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 105,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 106,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 107,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 108,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 109,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 110,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 111,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 112,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 113,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 114,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 115,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 116,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 117,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 118,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 119,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 120,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 121,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 122,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 123,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 124,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 125,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 126,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 127,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 128,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 129,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 130,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 131,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 132,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 133,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 134,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 135,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 136,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 137,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 138,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 139,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 140,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 141,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 142,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 143,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 144,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 145,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 146,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 147,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 148,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 149,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
  {
    id: 150,
    title: '',
    artist: '',
    cover: '',
    src: '',
  },
];

export default musicData;
